### ISSUE TITLE
[TODO] TAEDONG TODOLIST 10/03 

### ISSUE THREAD

**Issue by rlaxoehd4234** [DohoonHan/JMC#2]
- [x] 코드 컨벤션 작성 
 - [x] 요구사항명세서 작성(꿀팁 커뮤니티)
 - [x] 피그마 페이지 작성(꿀팁 커뮤니티)
 - [x] 챌린지 페이지 의논 (21시)

**Comment by rlaxoehd4234** [comment]
완료
