### ISSUE TITLE
[TODO] Meeting TODOLIST 10/4 14:00

### ISSUE THREAD

**Issue by rlaxoehd4234** [DohoonHan/JMC#3]
- [x] 피그마 페이지 작성 확인
- [x] 요구사항 명세서 작성 확인
- [x] ERD 준비 
- [x] 코드 컨벤션(깃, 코드) 확인
- [x] 깃 이슈 마일스톤 제작 
- [x] 깃 프로젝트 작성 및 기초 작업 
- [x] 서비스 소개글 작성 
- [x] 기술 스택 확립 및 루트 프로젝트 제작 후 깃 푸쉬
- [x] 깃허브 리드미 작성
- [x] 유즈케이스 작성
