### ISSUE TITLE
[TODO] 2024/10/09 TODOLIST

### ISSUE THREAD

**Issue by rlaxoehd4234** [DohoonHan/JMC#8]
- [x] 피그마 페이지 정리 
- [x] 요구사항명세서 작성 마무리 하기
- [x] 리액트 및 백엔드 공부하기
- [x] ERD 준비, 개인 페이지 확인하며 필요 필드 생각해오기

**Comment by rlaxoehd4234** [comment]
@DarWook @DohoonHan @sd8599 더 필요한 내용있으면 edit 해서 추가해주세여
